apiVersion: v1
items:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
      meta.helm.sh/release-name: astraakswp
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2021-09-10T13:47:35Z"
    generation: 1
    labels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: astraakswp
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mariadb
      helm.sh/chart: mariadb-9.5.1
    name: astraakswp-mariadb
    namespace: default
    resourceVersion: "23641"
    uid: a20ae183-7264-4c5a-8c9b-4c7c856e9d88
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: astraakswp
        app.kubernetes.io/name: mariadb
    serviceName: astraakswp-mariadb
    template:
      metadata:
        annotations:
          checksum/configuration: 66ec11f09110e4b8443a94e5b6d314d431a23e5fd7f8fd76c0273b28c7660e36
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: primary
          app.kubernetes.io/instance: astraakswp
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: mariadb
          helm.sh/chart: mariadb-9.5.1
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: primary
                    app.kubernetes.io/instance: astraakswp
                    app.kubernetes.io/name: mariadb
                namespaces:
                - default
                topologyKey: kubernetes.io/hostname
              weight: 1
        containers:
        - env:
          - name: BITNAMI_DEBUG
            value: "false"
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mariadb-root-password
                name: astraakswp-mariadb
          - name: MARIADB_USER
            value: bn_wordpress
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: mariadb-password
                name: astraakswp-mariadb
          - name: MARIADB_DATABASE
            value: bitnami_wordpress
          image: docker.io/bitnami/mariadb:10.5.12-debian-10-r32
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -ec
              - |
                password_aux="${MARIADB_ROOT_PASSWORD:-}"
                if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
                    password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
                fi
                mysqladmin status -uroot -p"${password_aux}"
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: mariadb
          ports:
          - containerPort: 3306
            name: mysql
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -ec
              - |
                password_aux="${MARIADB_ROOT_PASSWORD:-}"
                if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
                    password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
                fi
                mysqladmin status -uroot -p"${password_aux}"
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /bitnami/mariadb
            name: data
          - mountPath: /opt/bitnami/mariadb/conf/my.cnf
            name: config
            subPath: my.cnf
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1001
        serviceAccount: astraakswp-mariadb
        serviceAccountName: astraakswp-mariadb
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 420
            name: astraakswp-mariadb
          name: config
    updateStrategy:
      type: RollingUpdate
    volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: primary
          app.kubernetes.io/instance: astraakswp
          app.kubernetes.io/name: mariadb
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  status:
    collisionCount: 0
    currentReplicas: 1
    currentRevision: astraakswp-mariadb-645f9b4f57
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updateRevision: astraakswp-mariadb-645f9b4f57
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
