apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-anf-trident
  labels:
    app: nginx-anf-trident
    deploymethod: trident
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-anf-trident
  template:
    metadata:
      labels:
        app: nginx-anf-trident
        deploymethod: trident
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: disk01
          mountPath: /usr/share/nginx/html
      volumes:
      - name: disk01
        persistentVolumeClaim:
          claimName: anf-pvc
